messages:
  # Name to be sent in messages as the emitter
  # of the actions made with this instance
  emitter: "ethical hacker email or identifier"

  tools:
    pub:
      type: "rabbitmq"
      connection_string: ""
      queue: "tools"

  reports:
    pub:
      type: "rabbitmq"
      connection_string: ""
      queue: "tools"

storage_backend:
  tools:
    upload:
      type: "ftp"
      conf:
        user: "sarf"
        password: "sarf"
        host: "127.0.0.1"
        basedir: "/ftp/sarf/tools"

  reports:
    upload:
      type: "ftp"
      conf:
        user: "sarf"
        password: "sarf"
        host: "127.0.0.1"
        basedir: "/ftp/sarf/reports"

crud:
  companies:
    type: json
    conf:
      filename: ~/.sarf/data/companies.json

  projects:
    type: json
    conf:
      filename: ~/.sarf/data/projects.json

  reports:
    type: json
    conf:
      filename: ~/.sarf/data/reports.json

  vulnerabilities:
    type: json
    conf:
      filename: ~/.sarf/data/vulnerabilities.json

  vuln_templates:
    type: json
    conf:
      filename: ~/.sarf/data/vuln_templates.json
